# Generated by Django 6.1.1 on 2026-09-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('famille', models.CharField(help_text='ex: Prix, Technique, Partenariat', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAdverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(max_length=100)),
                ('taille', models.CharField(choices=[('TPE', 'TPE (< 10 rep.)'), ('PME', 'PME'), ('ETI', 'ETI'), ('GE', 'Grand Groupe')], max_length=3)),
                ('type_interlocuteur', models.CharField(help_text='ex: CEO, Acheteur, Technique', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Negociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_obtenu', models.FloatField(help_text='Résultat entre 0 et 100')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('arguments_utilises', models.ManyToManyField(to='predictor.argument')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.profiladverse')),
            ],
        ),
    ]
